### PR TITLE
fix(staking): correct validator fee in delegate modal

### LINKED ISSUE #254: Wrong validator commission in delegate modal
Commission value is always `10%`, which is wrong.

image

### PR DESCRIPTION
**Pull request by hadzhehsen**
closes: #254 
reference: HQW-10

### CODE REVIEW

File: libs/staking/validator-details-page/src/components/validator-info/validator-info.tsx [hunk 1]
```diff
@@ -547,6 +555,8 @@ export function ValidatorInfo({
     );
   }
 
+  console.log({ validatorCommission });
+
```
Comment (olegshilov) [inline libs/staking/validator-details-page/src/components/validator-info/validator-info.tsx]: remove

**Review by olegshilov — CHANGES_REQUESTED** [review]

File: libs/staking/validator-details-page/src/components/validator-info/validator-info.tsx (hunk 1 above)
Comment (hadzhehsen) [reply libs/staking/validator-details-page/src/components/validator-info/validator-info.tsx]: Done

**Review by olegshilov — APPROVED** [review]
